name: shared_preferences_cache_interceptor
description: Package to implements cache using shared preferences to hasura_connect package
version: 1.0.0-dev.4
homepage: https://flutterando.com.br
repository: https://github.com/Flutterando/shared_preferences_cache_interceptor

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0 <3.0.0"

dependencies:
  shared_preferences: ">=2.0.0 <3.0.0"
  hasura_cache_interceptor: ">=1.0.0-dev.5 <2.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  mocktail: ^0.0.1-dev.12
  # mockito: ^4.1.1
  flutter_test:
    sdk: flutter

flutter: